/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfirmDelete.java
 *
 * Created on 28-Nov-2012, 09:07:55
 */
package assortedComponents;

import calendarCode.Appointment;
import calendarCode.CalendarEx;
import is3calendar2.EditEventDialog;
import java.util.logging.Level;
import java.util.logging.Logger;

   
/**
 *
 * @author hector
 */
public class ConfirmDelete extends javax.swing.JDialog {

    
    private CalendarEx cal;
    private Appointment app; 
    private EditEventDialog di;
    /** Creates new form ConfirmDelete */
    public ConfirmDelete(java.awt.Frame parent, boolean modal, CalendarEx c, Appointment a, EditEventDialog d) {
        super(parent, modal);
        initComponents();
        cal = c;
        app = a;
        di = d;
    }
    public ConfirmDelete(){}
    
    public void setApp(Appointment a, CalendarEx c) {
        app = a;
        cal = c;   
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        noBut = new javax.swing.JButton();
        yesBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Are you sure you want to delete this appointment?");

        noBut.setText("No");
        noBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButActionPerformed(evt);
            }
        });

        yesBut.setText("Yes");
        yesBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(59, 59, 59)
                .add(noBut)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 197, Short.MAX_VALUE)
                .add(yesBut)
                .add(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(yesBut)
                    .add(noBut))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void noButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButActionPerformed
    this.dispose();
}//GEN-LAST:event_noButActionPerformed

private void yesButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButActionPerformed
    cal.removeAppointment(app);
    cal.saveCalendar("./cal");
    if (di != null) di.dispose();
    this.dispose();
}//GEN-LAST:event_yesButActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void run(final Appointment a, final CalendarEx calendar, final EditEventDialog d) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfirmDelete dialog = new ConfirmDelete(new javax.swing.JFrame(), true, calendar, a, d);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        try {
                            this.finalize();
                        } catch (Throwable ex) {
                            Logger.getLogger(ConfirmDelete.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton noBut;
    private javax.swing.JButton yesBut;
    // End of variables declaration//GEN-END:variables
}
